apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sureshben/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: json-web-token-secret
                  key: jwtkey
---
apiVersion: v1
kind: Service
metadata:
  name: auth-cluster-service
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
