apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: sureshben/expiration
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://expiration-mongo-cluster-service:27017/expiration'
            - name: NATS_URI
              value: 'http://nats-service:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: expiration-cluster-service
spec:
  selector:
    app: expiration
  ports:
    - name: expiration
      protocol: TCP
      port: 3000
      targetPort: 3000
